language: android
install: true
sudo: false

jdk:
    - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

cache:
  directories:
    - $HOME/.gradle

before_install:
  - openssl aes-256-cbc -K $encrypted_a21ff600c3ea_key -iv $encrypted_a21ff600c3ea_iv -in mobile/google-services.json.enc -out mobile/google-services.json -d

before_script:
  - chmod +x gradlew

script:
  - ./gradlew build

after_success:
  - ./gradlew jacocoTestReport && bash <(curl -s https://codecov.io/bash)
